# Site settings
title:          Philippines Private English Tutors
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "http://philippinesprivateenglishtutors.com/"

# Author
author:
  name:         Kevin Olega
  url:          https://olega.org/now
  email:        kevinolega@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title
paginate:       5
